@hostname = http://localhost
@port = 3002
@host = {{hostname}}:{{port}}
@contentType = application/json

@access-token = supersecretkey

# POST {{host}}/api/contacts/add_contact HTTP/1.1
# content-type: {{contentType}}
# access-token: {{access-token}}

#  {
#       "Formname":"test7 for data chaching",
#       "Fullname":"chinging7 mechanism ", 
#       "Number":"123456", 
#       "Email":"cache7@gmail.com", 
#       "Message":"hello message cache4"
# }

GET {{host}}/api/contacts HTTP/1.1
content-type: {{contentType}}
access-token: {{access-token}}


